services:
  pazar-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pazar-backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/pazardb
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - pazar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pazar-frontend-app
    ports:
      - "5173:3000"
    depends_on:
      - pazar-backend
    restart: unless-stopped
    networks:
      - pazar-network

  mongodb:
    image: mongo:latest
    container_name: pazar-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pazar-network
    restart: unless-stopped

networks:
  pazar-network:
    driver: bridge

volumes:
  mongodb_data:

