services:
  pazar-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pazar-backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    networks:
      - pazar-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pazar-frontend-app
    ports:
      - "5173:3000"
    depends_on:
      - pazar-backend
    restart: unless-stopped
    networks:
      - pazar-network

networks:
  pazar-network:
    driver: bridge

